const personModels = require('../models/personModel');
const personSchema = require('../schemas/personSchema');

const getPerson = async (req, res) => {
    const { sortBy } = req.query;
    if(sortBy) {
        const { error } = personSchema.sortPersonSchema.validate({sortBy});
        if (error)
            return res.status(400).send({ message: error.details[0].message });
    }
    try {
        const result = await personModels.selectPerson(sortBy);
        if (result.rows.length < 1)
            return res.status(200).send({ message: "V databÃ¡ze sa nenachÃ¡dzajÃº Å¾iany Ä¾udia."});

        return res.status(200).json(result.rows);
    } catch (e) {
        console.log(`ðŸŸ  We got a problem: ${e}`);
        return res.status(500).send({message: "Neocakavana chyba na strane databazy."});
    }
};

const getPersonByID = async (req, res) => {
    const { id } = req.params;
    const { error } = personSchema.sortPersonIdSchema.validate({id});
    if(error)
        return res.status(400).send({ message: error.details[0].message});
    try {
        const result = await personModels.selectPersonById(id);
        if(result.rows.length < 1) 
            return res.status(200).send({ message: "V databÃ¡ze sa konkrÃ©tny klub" })
        return res.status(200).json(result.rows);
    } catch (e) {
        console.log(`ðŸŸ  We got a problem: ${e}`);
        return res.status(500).send({message: "Neocakavana chyba na strane databazy."});  
    }
};
const createPerson = async (req, res) => {
    const { error } = personSchema.createPersonSchema.validate( req.body );
    if(error)
        return res.status(400).send({ message: error.details[0].message});

    const { name, surname, birth, club } = req.body;
    try {
        const result = await personModels.insertPerson(name, surname, birth, club)    
        if(result.rows.length < 1) 
            return res.status(200).send({ message: "Nebolo moÅ¾nÃ© zapÃ­saÅ¥ osobu do databÃ¡zy"});

        return res.status(201).send({ message: "UÅ¾ivateÄ¾ bol ÃºspeÅ¡ne vytvorenÃ½ v databÃ¡ze."});
    } catch (e) {
        console.log(`ðŸŸ  We got a problem: ${e}`);
        return res.status(500).send({message: "Neocakavana chyba na strane databazy."});
    }    
};
const editPerson = async (req, res) => {

};
const deletePerson = async (req, res) => {

};



module.exports = { getPerson, getPersonByID, createPerson, editPerson, deletePerson };